### ISSUE TITLE
New RK-9 

### ISSUE THREAD

**Issue by littleguideboi** [hsdn/tera-guide#10]
FYI, new RK-9 guide is not working on last boss

**Comment by littleguideboi** [comment]
I mean it has no errors but no messages as well at all

**Comment by shindmitry** [comment]
I know. We will be adding full functionality soon.

**Comment by littleguideboi** [comment]
thanks for the feedback!

**Comment by AshantyTTV** [comment]
For a few users is working. We got messages. SpawnObjects but sometime message is not corect or it spawnObject and no call out

**Comment by shindmitry** [comment]
@AshantyTTV Do you mean S-attacks on the last boss?

**Comment by littleguideboi** [comment]
yea everything works on 1st and 2nd boss but 3rd boss's calls are still buggy and calling wrong

**Comment by AshantyTTV** [comment]
I dont know. I did couple of runs and i died on safe spot. Was S left and i died on left. Was S right and i died on right. I had to move a bit more to take distance. Also cals aren't good. Sometime it says the callings. Sometime doesnt. Or it says and are wrong. 
Now maybe im wrong. Hope to be fixed soon

**Comment by AshantyTTV** [comment]
I think it got updated. :D

**Comment by littleguideboi** [comment]
It still calls wrong

**Comment by AshantyTTV** [comment]
yeah it does calls wrong. i will wait for a fixed update. this guys are working hard for it.

**Comment by littleguideboi** [comment]
guide is not calling anything on Last boss now

**Comment by shindmitry** [comment]
All messages for the last boss are temporarily disabled. The work is in progress.

**Comment by shindmitry** [comment]
We update guide. Please test.

**Comment by shindmitry** [comment]
The update has been released. Please test.

**Comment by PepegaHah** [comment]
I tested out shindmitry. Somehow for example in his first attack he says directly "IN+ Waves" or "IN-+OUT" etc. anything. But somehow after the first mechanic he just doesnt say anything after that. Just randomly IN or OUT calls.

**Comment by shindmitry** [comment]
Have you tested now? We uploaded the update 20 minutes ago, all mechs works fine.

**Comment by PepegaHah** [comment]
I've just tested out when you updated it like 30 seconds ago it says. In first mech it is so pure as i said IN + Waves for example. But after that, it doesn't say. I should replace it again i guess cuz i dont use it on auto update. But i'm sure i've replaced whenever you relased the new one tho.

**Comment by Ana-s2** [comment]
О Hsdn always does a great job, I know the guides well and I know that this is a huge job I recognize, I hope you can do it. You are fabulous <3

**Comment by littleguideboi** [comment]
I tested it and it works perfect! Thanks for the support <3

**Comment by shindmitry** [comment]
Processing of triple S-attacks after 70% may be not work correctly. The work is in progress.
