### ISSUE TITLE
handle: failed to parse S_SPAWN_NPC<*>

### ISSUE THREAD

**Issue by DHuangs** [hsdn/tera-guide#102]
hello, i used this mod in menma server,and the following error occurs, may you tell me how to solve it? Thank you.

[dispatch] [tera-guide] handle: failed to parse S_SPAWN_NPC<*>
hook: (anonymous) in tera-guide
data: 970078cf00000000000000008700de250200d0800c000000000000000000ab5cfbc70833bf470040514500000c00000095010000f4020000000000000000000000002173adf4050000000100010000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000100000001000000000024c674b974ce5f00d0c615d66cad0000
error: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at Object.eval (F:\Program Files\MT - The Dream\toolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:1:1
    at TeraProtocol.parse (F:\Program Files\MT - The Dream\toolbox\node_modules\tera-data-parser\lib\protocol\index.js:253:46)

**Comment by justkeepquiet** [comment]
Hi. For stable operation of all modules we recommended to use this version of the TeraToolbox: https://github.com/tera-private-toolbox/tera-toolbox

**Comment by DHuangs** [comment]
ok,I'm currently using toolbox of menma launch ,I'll use this version , if this problem still exists, I will respond again.
Thank you.
