### ISSUE TITLE
Settings migration issue

### ISSUE THREAD

**Issue by DelliriumX** [hsdn/tera-guide#103]
I've downloaded and am using starscape tera toolbox (v92/100) and using the "Get More Mods" page, I've installed Tera Guides.

Upon starting, it required that "Tera Guides Core" be installed. ( I was under the impression that Toolbox installs dependencies automatically). Anyways, since that one is NOT in the list, i had to install it manually, so I did. In the manual installation it was also asked to replace the "library" so I did that as well.

Upon attempting to start, the toolbox complains about missing "settings migration"

I've attached to [log](https://github.com/hsdn/tera-guide/files/15359705/teralog.log) file.

![image](https://github.com/hsdn/tera-guide/assets/11763983/f52bca23-ff00-4dd4-be5d-1f2fa2e1a37e)

**Comment by DelliriumX** [comment]
I've come to realization that this is not specific to this mod, any mod I attempt to "add" on top of what comes preinstalled with Toolbox has the same treatment (when adding them via toolbox's install - not manually).

I have no idea why but mods cannot be installed with Toolbox, have to do it manually.

**Comment by justkeepquiet** [comment]
Hi. This problem can occur when the antivirus causes a false positive. You need to disable it or exclude the toolbox directory from scanning.

**Comment by DelliriumX** [comment]
I've added the toolbox to the exceptions on the AV, but when I attempt to install it, same thing happens, my mods folder only gets the `module.json` file and all the other files are missing.

**Comment by justkeepquiet** [comment]
You probably have automatic updates turned off. Modules cannot be installed if updates are disabled.

**Comment by justkeepquiet** [comment]
Looking at your log, I see this entry:
```
[05:42:39.776] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!!!!!!!!!!!!!!!!!!!!!!!
[05:42:39.776] !!!!! YOU HAVE GLOBALLY DISABLED AUTOMATIC UPDATES!!!!!
[05:42:39.777] !!!!! THERE WILL BE NO SUPPORT FOR ANY KIND OF PROBLEM THAT!!!!!
[05:42:39.777] !!!!! YOU MIGHT ENCOUNTER AS A RESULT OF DOING SO!!!!!
[05:42:39.777] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by DelliriumX** [comment]
Oh okay, let me give this a try

**Comment by DelliriumX** [comment]
I've managed to get this to work with your instructions.
In the end it was the updates settings, it just required a restart on top of it. Don't know why, possible I messed something up.

For anyone facing the same issue:

- Enabling auto updates + AV exception is what worked for me.

Thanks.
