### ISSUE TITLE
toolbox error

### ISSUE THREAD

**Issue by dxmantastyle** [hsdn/tera-guide#15]
20:30:00.081] [mods] ERROR: Module "tera-guide-master" could not be preloaded!
[20:30:00.081] [mods] ERROR: Please contact the module's author: https://discord.gg/659YbNY
[20:30:00.084] Error: Cannot find module 'C:\Users\Darren\AppData\Local\Programs\TeraToolbox\mods\tera-guide-master'
Require stack:
- C:\Users\Darren\AppData\Local\Programs\TeraToolbox\bin\mod.js
- C:\Users\Darren\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js
- C:\Users\Darren\AppData\Local\Programs\TeraToolbox\bin\proxy.js
- C:\Users\Darren\AppData\Local\Programs\TeraToolbox\bin\loader-gui.js
- C:\Users\Darren\AppData\Local\Programs\TeraToolbox\bin\index-gui.js
- C:\Users\Darren\AppData\Local\Programs\TeraToolbox\node_modules\electron\dist\resources\default_app.asar\main.j

**Comment by shindmitry** [comment]
You need install https://github.com/tera-toolbox-mods/library or reinstall tera-guide module first.
