### ISSUE TITLE
3026-3126 CSN/H Suggestion

### ISSUE THREAD

**Issue by PepegaHah** [hsdn/tera-guide#16]
Hello shindimitry,

Thanks for the great work, i do appreciate a lot. But i wonder is it possible to change messages "60 degrees (Fire) to 60 Degrees Take Ice (or just "Take Ice") and 40 degrees (Ice) to 40 Degrees Take Fire (or just "Take Fire" ). I know not much really needed. Buıt instead of what it is (cuz it is obvious that boss gives fire and its able to see the degree bar is high or low), that might be better. Just a suggestion tho o/

**Comment by shindmitry** [comment]
Hi,

This messages simply informs that there will be an AOE applying fire or ice to all players. Which debuff to take to whom depends on the situation. In hard mode it is not always necessary to change your debuff. Therefore, asking everyone to change the debuff at once is incorrect (in particular, for hard mode).

**Comment by shindmitry** [comment]
May be added an additional message to notify that the temp is rising or falling.

**Comment by PepegaHah** [comment]
Yeah might last notice can be as well as you said.

**Comment by shindmitry** [comment]
This messages added in the latest update.
