### ISSUE TITLE
marking out of order

### ISSUE THREAD

**Issue by Ana-s2** [hsdn/tera-guide#17]
Hi, in the bahaar guide (9044) there is an attack called
"Front | Left Scratch"
in which the marking is a little out of order, that is to say marks in one place but goes in another, although the difference is little, if you could fix it.  thanks.

**Comment by Loliconera** [comment]
Ana-s2
I think that for that you should consult with the original author of the guide called: Michengs?

**Comment by shindmitry** [comment]
Hi, we will check soon.

**Comment by Ana-s2** [comment]
Hello, I haven't tested it yet, to see if it looks good and I'm sorry, already commenting like this, but yesterday after a few hours with my wife, I managed to add something ... for the
"Front | Left Scratch", in my view, it would be perfect.
I will post here, if you accept a suggestion, can you test for the "Front | Left Scratch" attacks please
	

	
"s-444-1000-2131-0": [{"type": "text","sub_type": "message","message": 'Front | Left Scratch ',"message_RU": "Удар в вперед | Левый черкаш"},
	         {"type": "func","func": SpawnCircle.bind(null,false,553,358,340,6,630,100,4000)},
	         {"type": "func","func": SpawnVector.bind(null,553,90,115,185,800,0,4000)},
	         {"type": "func","func": SpawnVector.bind(null,553,90,115,5,300,0,4000)},
	         {"type": "func","func": SpawnVector.bind(null,553,270,250,5,300,0,4000)},
	         {"type": "func","func": SpawnVector.bind(null,553,270,250,185,800,0,4000)}
	],

for the attack, "Front | Right Scratch" I can't do it ... if you like my modification / suggestion, you can add it to "Front | Right Scratch"

I'm sorry for doing this, I hope you're not upset, I know you do a great job, I just wanted to try to help

**Comment by salman90299** [comment]
hi can we have indicator on floor for main one shot mechanics only for some dungeons? and dah indicators for circle is inaccurate it seems

**Comment by shindmitry** [comment]
Hi,
> dah indicators for circle is inaccurate it seems
@salman90299, what kind of mechanics talking about?

**Comment by salman90299** [comment]
> 
> 
> Hi,
> 
> > dah indicators for circle is inaccurate it seems
> 
> @salman90299, what kind of mechanics talking about

its the 1st back and front attack he does after drawing the circle on the floor the edges are inaccurate with the latest update

**Comment by shindmitry** [comment]
@salman90299, the markers are moved forward of the boss or is radius of semicircle wrong?

**Comment by salman90299** [comment]
the > < markers are moved forward

**Comment by shindmitry** [comment]
We fix this in the latest update. Please check.

**Comment by shindmitry** [comment]
@Ana-s2 hi, your code has not been tested yet, it may take time.

**Comment by Ana-s2** [comment]
hi, ok no problem, do it when you have time, i'll be waiting ^-^

**Comment by salman90299** [comment]
> 
> 
> We fix this in the latest update. Please check.

yes this has been fixed

**Comment by shindmitry** [comment]
@Ana-s2, Markers for scratch-attacks has been updated https://github.com/hsdn/tera-guide/commit/0d7cea267067c16ccf6adc02dd3db80412bbfd2f. You can check this.

**Comment by Ana-s2** [comment]
hi, thank you for improving <3
