### ISSUE TITLE
RKE

### ISSUE THREAD

**Issue by PepegaHah** [hsdn/tera-guide#18]
Hello shindimitry,

The RKE module is working absolute find but sometimes it tells wrong. For example in the RKE last boss guide said Out+In but boss did the opposite way (and people died). Do you think there can be a bug? Or it was just i dunno, classic TERA bug?

**Comment by shindmitry** [comment]
Hi,

The script simply monitors the mechanics (Quest Balloons or Dungeon Messages) and displays their sequence as it is. During the clearing of the dungeon, there were situations when the boss changed the number from 0 to 1 or 1 to 0 at the time of the in/out/wave mechanics, which caused the party to die (the script will not have time to process this and will display incorrect info). In fact, this is a TERA bug and cannot be fixed.
