### ISSUE TITLE
Forbidden Arena-UW

### ISSUE THREAD

**Issue by PepegaHah** [hsdn/tera-guide#22]
Hello shindimitry,
Thank you for the great and fast work i do appreciate a lot. But there is a thing i wanna ask in normal mode of Brawler dungeon. Under %70 he does Flying Kick (stun) also under 30 he does double punch+uppercut. Is it possible to add those?

**Comment by shindmitry** [comment]
Hi,
We've added notices for base attacks to tank:
```js
"s-3203-1000-113-0": [{"type": "text","class_position":"tank","sub_type": "message","message": "Roundhouse kick","message_RU": "Удар с разворота"}],
"s-3203-1000-121-0": [{"type": "text","class_position":"tank","sub_type": "message","message": "Flip kick","message_RU": "Удар в воздухе"}],
"s-3203-1000-111-0": [{"type": "text","class_position":"tank","sub_type": "message","message": "Knockdown","message_RU": "Опрокид"}],
"s-3203-1000-102-0": [{"type": "text","class_position":"tank","sub_type": "message","message": "Combo","message_RU": "Комба"}],
"s-3203-1000-115-0": [{"type": "text","class_position":"tank","sub_type": "message","message": "Front kick","message_RU": "Удар вперед"}],
"s-3203-1000-153-0": [{"type": "text","class_position":"tank","sub_type": "message","message": "Two kicks","message_RU": "Два удара"}],
```
A stun/knockdown notices are displayed anyway. If there is any mistake, please tell me.

**Comment by PepegaHah** [comment]
Oh  i see. But instead of Flip Kick you still can write stun. Cuz it had to be iframed or outranged. Abd the one i was talking about also was knock up not knockdown. Under %30 tho i should try and see again today o/

**Comment by shindmitry** [comment]
>But instead of Flip Kick you still can write stun

Added https://github.com/hsdn/tera-guide/commit/efe4d41166c750e606aa4e215d43d1a70c01c663

**Comment by PepegaHah** [comment]
Gonna be trying otu today

**Comment by shindmitry** [comment]
> Abd the one i was talking about also was knock up not knockdown. 

You are about this https://imgur.com/a/l1K21Jb (the last attack)?

**Comment by Kasdal** [comment]
Could you please add timer alert for Ha! attack. Its on 70 sec cooldown? Like maybe on 60 sec Ha! attack soon.

**Comment by shindmitry** [comment]
@Kasdal, Added https://github.com/hsdn/tera-guide/commit/2cab2d30b7080854e1d8bcc00b116de31d5be338

**Comment by Kasdal** [comment]
Wow, that was super fast. Thank you!!
