### ISSUE TITLE
Ping increase due to setTimeout() being used incorrectly

### ISSUE THREAD

**Issue by HakuryuuDom** [hsdn/tera-guide#24]
turns out this module will actually increase your ping. consider using `mod.setTimeout()` which auto clears on leaving the game or clearing timeouts correctly -Haku

**Comment by shindmitry** [comment]
Hi,
In practice, all the values for the setTimeout() do not exceed a few seconds, so in theory the functions will end after the dungeon is cleared. There is also a method for automatic clearing timeouts in clearTimeout() for all delays when changing zones or leaving the dungeon (except for some used in lib.js and some guide files).

We will consider replacing from base function setTimeout() to mod.setTimeout() if necessary.

**Comment by shindmitry** [comment]
We've added a global wrapper to operate all timeouts in all scripts. Now all timers are always cleared when changing zones or relog.
