### ISSUE TITLE
DAH backwards donuts

### ISSUE THREAD

**Issue by gamerstuff** [hsdn/tera-guide#25]
the in>out & out>in donuts waves in DAH are flipped backwards in your guide....
so for example when the notice message "Donuts: In > Out"  comes up, the boss does the out>in donuts mechanic, 
and the message "Donuts: Out > In" comes up when the in>out donuts mechanic happens

**Comment by shindmitry** [comment]
The guide informs about where the safe-zone for the player ("in>out" for inward waves, or "out>in" for outward waves), in accordance with the basic style of displaying mechanics in other guides.

Additionally, we have added a text about the direction of the waves.
