### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Amethsya** [hsdn/tera-guide#27]
![hata](https://user-images.githubusercontent.com/67187220/92281338-0a4dcd00-ef04-11ea-97e1-7d9818eab7a7.JPG)

I was doing csn run and everytime boss doing ice/fire in and out mecha, i got this error msg every single time. Maybe because i havent updated the mod today yet. I just wanted to let u know.

**Comment by shindmitry** [comment]
Hi,
This has been fixed in recent updates https://github.com/hsdn/tera-guide/commit/3b2cdd55b423785886bc7cfb9376acb5afc1902c.
Please check for updates.
