### ISSUE TITLE
command guide gui

### ISSUE THREAD

**Issue by Ana-s2** [hsdn/tera-guide#29]
hi, I can't use the 'guide gui' commands
when I try to activate something through the GUI interface, nothing happens, just go out in the chat (toolbox)
can you tell me if it is working correctly?

**Comment by shindmitry** [comment]
Hi,
Check for updates on the guide and Toolbox.
To implement the GUI is used built-in client functionality, so everything should work.

**Comment by Loliconera** [comment]
The GUI guide does not work for me either, only the window appears but it does not seem to do anything.

**Comment by shindmitry** [comment]
If you are using the fps-utils module, try entering the **fps gui** command.
If the interface will not display, this is probably a basic problem.

**Comment by Ana-s2** [comment]
so ... the GUI interface appears, however when we press to have a desired function nothing happens
just appears in the chat (toolbox)

**Comment by shindmitry** [comment]
The GUI simply sends commands to the chat, just as if you had manually sent them. The chat will contain information about whether the option you clicked has turned On or Off.

Also try sending the desired (eg. **guide voice**) command to the chat directly and see the result.

**Comment by Ana-s2** [comment]
I upgraded to the last version 2 hours ago, but for some reason, it still doesn't work, it opens but when I press a command it stays like this, nothing changes or happens
sorry.

https://i.imgur.com/vsTzPsQ.png

**Comment by Loliconera** [comment]
I solved the problem, installing the fps-util module

**Comment by Ana-s2** [comment]
I have fps-util, and it doesn't work, without wanting to be rude or badly grateful .... but I shouldn't depend on another mod to work

**Comment by Loliconera** [comment]
the fps-util module, it has its fps-GUI version and if the buttons work.

**Comment by Loliconera** [comment]
try reinstalling the toolbox

**Comment by shindmitry** [comment]
It works fine for us without the fps-utils module installed.

**Comment by Loliconera** [comment]
I will try to uninstall the fps-useful module

**Comment by Ana-s2** [comment]
haha, i already got lost, does it work with fps utils or without?

**Comment by Loliconera** [comment]
I just uninstalled the fps-util module and now the buttons in the guide-GUI window no longer work.

**Comment by Loliconera** [comment]
the guide-gui window DOES NOT WORK THE BUTTONS if you do not have fps-util.

**Comment by Loliconera** [comment]
It's very weird

**Comment by Ana-s2** [comment]
yes, It's very weird

**Comment by Loliconera** [comment]
It seems that the guide-GUI window depends on the FPS-UTIL module for the buttons to work.

**Comment by shindmitry** [comment]
This is probably due to the lack of processing in C_ADMIN.

**Comment by shindmitry** [comment]
We've added the necessary hooks to the update. Please update script now check if it works.

**Comment by Loliconera** [comment]
ok

**Comment by Loliconera** [comment]
ready, the buttons work perfectly.

**Comment by shindmitry** [comment]
Good. Thanks for contribution.

**Comment by Ana-s2** [comment]
what a pity, for me it still doesn't work, but that's ok, thanks

**Comment by shindmitry** [comment]
@Ana-s2, Try to reinstall you Toolbox. 

We tested the latest version of the module on the newly installed Toolbox.

![](https://i.imgur.com/oR4Dzhu.png)

The buttons in GUI worked fine.

**Comment by Loliconera** [comment]
try restarting the toolbox or reinstalling it from 0.

**Comment by Ana-s2** [comment]
ok, i will try, and i will come back here soon to confirm, thanks

**Comment by Ana-s2** [comment]
thank you very much, now it works, and I'm sorry, although before I really wasn't, but now it's 100%, thanks <3

**Comment by shindmitry** [comment]
Thanks for testing.
