### ISSUE TITLE
Did it ever occur to you to add the Spanish language?

### ISSUE THREAD

**Issue by Loliconera** [hsdn/tera-guide#31]
For example, in my case, I have to translate the entire module from the English / Russian language to the native language, which for me is Spanish.

I recorded some videos where you can see the translation into Spanish made by me.
https://www.youtube.com/watch?v=VxqPmgbf4dw&t=97s&ab_channel=GustavoSicha
https://www.youtube.com/watch?v=EnG2cTIPJTc&t=4s&ab_channel=GustavoSicha

**Comment by shindmitry** [comment]
Hi,
Our team does not have people who know Spanish. 
You can translate the **all files** yourself, and if possible, we will add support for this language.
We will also need to add feature for a manual language selection, since Spanish is not supported by the Tera client by default.

**Comment by Loliconera** [comment]
uhm yeah you're right

**Comment by Loliconera** [comment]
here is the mod with the spanish translation, only a few dungeons have been translated into spanish

Dungeons Soportados
-Velik's Sanctuary
-Red Refuge                                                   <- Español
-RK-9 Kennel                                                 <- Español 
-RK-9 Kennel (Rampaging)                        
-Antaroth's Abyss (Hard)
-Grotto of Lost Souls (Hard)
-Bahaar's Sanctum
-Gossamer Vault (Hard)
-Akalath Quarantine                                     <- Español
-Sea of Honor                                                 <- Español
-Corrupted Skynest                                       <- Español
-Corrupted Skynest (Hard)
-Draakon Arena
-Draakon Arena (Hard)
-Forbidden Arena [Hagufna]                       <- Español 
-Forbidden Arena [Undying Warlord]
-Forbidden Arena [Nightmare Undying Warlord]
https://drive.google.com/file/d/1wiD4KfDGzv3tq8u7GqNwaLE7zLLNeASQ/view?usp=sharing

**Comment by Multarix** [comment]
It would be easier to upload your modifications to github so we don't have to download them directly... But as for changing the language manually, it could be done somewhat easily by adding a language selection via the config file with a few changes. Eg a config setting that is by default set to "auto" but if set to Spanish, English, Russian etc it uses that.

**Comment by Loliconera** [comment]
uhmm interesting

**Comment by Loliconera** [comment]
I have never tried to upload the modded tera guide (hsdn) module to Spanish to GitHub

**Comment by Multarix** [comment]
That's no problem, git/ github can be a bit confusing so I'm not asking you to do it, just letting you know as it allows us to look over code/ translations without having to download anything.

I'm also not in charge of making any choices for what gets added to this guide or not, so the end choice it's not up to me.

**Comment by Loliconera** [comment]
ok, then I'll continue translating the other missing dungeons.

**Comment by Loliconera** [comment]
I will try to make a copy of the tera guide (hsdn) to the github of my personal account and translate it into Spanish

**Comment by shindmitry** [comment]
>But as for changing the language manually, it could be done somewhat easily by adding a language selection via the config file with a few changes. Eg a config setting that is by default set to "auto" but if set to Spanish, English, Russian etc it uses that.

@Multarix, this feature is added in latest updates, but yet not supported in settings_migrator.

We've also added automatic loading of dungeon names from Tera client, so no names translation is required.

**Comment by shindmitry** [comment]
@Loliconera, 
For adding a Spanish language to guide files, you need to use a "message_ES" keys instead of "message".
To apply Spanish language to module, please update module to latest version and set parameter **language** in config.json to **es**.

**Comment by shindmitry** [comment]
We have done work on the simplest possible integration of any language, including non-standard (for the Tera) languages.

**Comment by Loliconera** [comment]
Hello, I just made a copy of your module and I modified it to Spanish and uploaded it to my Github profile.
Here is the repository https://github.com/Loliconera/tera-guide-spanish

You can look at it if you like, because the truth is I am a bit new to creating repositories in github

**Comment by shindmitry** [comment]
If you finish translating all the files and follow the format suggested above ("message_ES" instead of "message" for Spanish), we can include your work in master branch of the guide. And the index.js will look good.

**Comment by Loliconera** [comment]
I spent an hour trying to understand what you mean by ("message_ES" instead of "message" for Spanish) until I reviewed a guide to a dungeon and discovered that format
haha

**Comment by shindmitry** [comment]
All guides are based on the JSON structure, which describe the necessary mechanics and other reactions in the dungeons.
Each such entry can contain a message for the player in several languages.
 
Different keys are used to separate languages, starting with **message_**, for example **message_RU**.
 
For example, for a Draakon Arena 3102.js dungeon, we can define a single entry as:
  ```
    "s-3102-1000-107-0": [
        { 
            "type": "text", 
            "sub_type": "message", 
            "message": "Spectral Throw (Bait)", 
            "message_RU": "Спектральный бросок (байт)" 
        }
    ],
```
Where the text is presented in many languages, given by different keys:  
**message** for English (by default) and **message_RU** for Russian.
 
To add a Espanol translation, you need to add a record (idk words, this is just example):
 ```
            , "message_ES": "Lanzamiento espectral (cebo)"
 ```
To make the object look like this:
 ```
    "s-3102-1000-107-0": [
        { 
            "type": "text", 
            "sub_type": "message", 
            "message": "Spectral Throw (Bait)", 
            "message_RU": "Спектральный бросок (байт)",
            "message_ES": "Lanzamiento espectral (cebo)" // <-- added Espanol translation record
        }
    ],
  ```
Or single line (variant, like records in the all guide files):
 ```
    "s-3102-1000-107-0": [{ "type": "text", "sub_type": "message", "message": "Spectral Throw (Bait)", "message_RU": "Спектральный бросок (байт)", "message_ES": "Lanzamiento espectral (cebo)" }],
```

**Comment by Loliconera** [comment]
ok

**Comment by shindmitry** [comment]
You need now to get "clean" files from the latest version of the guide and add your translation with the "message_ES" keys to them.

**Comment by shindmitry** [comment]
Also you can contact with https://github.com/Ana-s2, this person also plans to work on a translation guides into Spanish and Portuguese.

**Comment by Loliconera** [comment]
I only translate into Spanish language nothing else

**Comment by Loliconera** [comment]
ready now if it is working with the message_ES format

**Comment by Loliconera** [comment]
In this code I don't know how to create a format in Spanish
`0: { msgt: "IN",  msg: "К НЕМУ" }`

**Comment by shindmitry** [comment]
Don't touch it yet. You can write a translation in the comments to it, we will fix it.

**Comment by Loliconera** [comment]
OK thanks

**Comment by Loliconera** [comment]
acabo de agregar las traducciones al español siguiendo el formato message_ES

https://github.com/Loliconera/tera-guide-spanish


-Red Refuge <- Español
-RK-9 Kennel <- Español
-Akalath Quarantine <- Español
-Sea of Honor <- Español
-Corrupted Skynest <- Español
-Forbidden Arena [Hagufna] <- Español

**Comment by shindmitry** [comment]
@Loliconera, we make changes for "msgt" and "msg" keys. Please check https://github.com/hsdn/tera-guide/commit/a588ee8a6c05adcbe8c409d7c3ae100f82b10577.
You can use this variant in your translation.

**Comment by Loliconera** [comment]
Perfect, thanks
