### ISSUE TITLE
Manifest generator

### ISSUE THREAD

**Issue by Loliconera** [hsdn/tera-guide#34]
What version of manifest generator are you using?

**Comment by shindmitry** [comment]
We use this https://github.com/EricBanker12/manifest-generator

**Comment by Loliconera** [comment]
Do I have to configure something special in manifest.js?

**Comment by Loliconera** [comment]
or do I just run manifest.bat?

**Comment by shindmitry** [comment]
Not required, just run bat file in root directory of the module.

**Comment by Loliconera** [comment]
Perfect, thanks
