### ISSUE TITLE
Color of Raid notice

### ISSUE THREAD

**Issue by fisherman1717** [hsdn/tera-guide#37]
is there a way to change the color of the Raid notice font that appears at bottom middle of screen?
not the one that appears in the bottom left chat.
Wish to change it from blue to bright yellow.

**Comment by shindmitry** [comment]
Raid leader noticrs are displayed in yellow by default. You can change the color in the Tera chat settings.
![](https://i.imgur.com/5gq5PUH.png)

**Comment by fisherman1717** [comment]
yes my raid leader color is selected to yellow, but the words that appear in the middle-bottom of the screen are blue.

**Comment by fisherman1717** [comment]
![image](https://user-images.githubusercontent.com/56363148/93601195-62e89400-f9f3-11ea-9f95-b813e3b2218a.png)

This is the one i mean - it's blue.

**Comment by shindmitry** [comment]
If you have **lNotice** is enabled, then the messages at the bottom are displayed as party leader notices. I don't know how to change this color.
