### ISSUE TITLE
3034 - Rampaging RK-9 Kennel

### ISSUE THREAD

**Issue by Ana-s2** [hsdn/tera-guide#40]
Hi, I still don't do this DG, but my friend went to do it yesterday and came across this error, and sent me this print, yesterday morning, you made changes to the code in general, I don't know if it was because of that, if it wasn't I'm sorry, thank you

Here: https://i.imgur.com/yTKPb3M.png

**Comment by shindmitry** [comment]
Hi,
We not have any changes to this guide code. 
You may have made a mistake in your translation, try to download and replace index.js and 3034.js.

**Comment by Ana-s2** [comment]
thanks for answering, i will check.
