### ISSUE TITLE
New update made the guide go poof

### ISSUE THREAD

**Issue by LeGiam** [hsdn/tera-guide#42]
with the update on the 30th the guide doesnt load anymore , says something about "core thingy not being there" when i already have it installed

**Comment by PsykoDev** [comment]
https://github.com/hsdn/tera-guide/tree/7096d1f369e5230c14eb839b59d5513fbee35d2a use this version and disable auto update for now

**Comment by shindmitry** [comment]
Please check https://github.com/hsdn/tera-guide/issues/43
