### ISSUE TITLE
Initialized dependency

### ISSUE THREAD

**Issue by phurso** [hsdn/tera-guide#47]
When I launch tera toolbox it will keep doing 

[12:26:12.847] [update] Initialized dependency "tera-guide-core" for module "tera-guide"
[12:26:13.392] [update] Initialized dependency "tera-guide-core" for module "tera-guide"
[12:26:13.938] [update] Initialized dependency "tera-guide-core" for module "tera-guide"
[12:26:14.474] [update] Initialized dependency "tera-guide-core" for module "tera-guide"
[12:26:15.010] [update] Initialized dependency "tera-guide-core" for module "tera-guide"
[12:26:15.560] [update] Initialized dependency "tera-guide-core" for module "tera-guide"

it wont stop and actually do it.  Am I doing something wrong? do I simply need to wait?

**Comment by jk-q** [comment]
Try to run Toolbox as administator. Also check your antivirus, firewall and internet connection.
We check now on fresh installed TeraToolbox, no problem detected.

Also you can install tera-guide-core module manually. 
Go here https://github.com/hsdn/tera-guide-core for this.

**Comment by phurso** [comment]
[image: image.png]

I tried as admin and I tried without antivirus and  firewall and internet
connection is fine my tera toolbox works like usual except when I have that
folder in my files and I did instal it manually.

Le lun. 12 oct. 2020, à 12 h 36, Dmitry Shin <notifications@github.com> a
écrit :

**Comment by jk-q** [comment]
The folders for the module and dependencies (located in **mods**) should be named like this:
**library**
**tera-guide-core**
**tera-guide-master**

If auto-installation not worked, you need install module and dependencies manually. Also you can try to reinstall toolbox.

**Comment by phurso** [comment]
I have library and I renamed tera-guide-master to tera-guide-core like
mentioned in github I wasn't supposed to do that?
where can I find the original tera-guide-core?

Le lun. 12 oct. 2020, à 12 h 47, Dmitry Shin <notifications@github.com> a
écrit :

**Comment by jk-q** [comment]
**tera-guide-master** is not **tera-guide-core**, this is a different modules. 
You need both modules for correct working the guide.

**Comment by phurso** [comment]
alright I installed them both but now it gives me this error not sure what
to do
[image: image.png]

Le lun. 12 oct. 2020, à 12 h 55, Dmitry Shin <notifications@github.com> a
écrit :

**Comment by jk-q** [comment]
The **tera-guide-core** and **library** installed automatically.
You NOT need manually download it's folders. Delete them if downloaded earlier.

And just download **tera-guide-master** and place it in the **mods** folder. Restart Toolbox.

**Comment by phurso** [comment]
[image: image.png]

[image: image.png]
 still gives me a error



Le lun. 12 oct. 2020, à 13 h 19, Dmitry Shin <notifications@github.com> a
écrit :

**Comment by phurso** [comment]
nvm im just dumb

Le lun. 12 oct. 2020, à 13 h 42, MAD GENESIS <madgenesis25@gmail.com> a
écrit :

**Comment by phurso** [comment]
I think it works now thank you very much

Le lun. 12 oct. 2020, à 13 h 43, MAD GENESIS <madgenesis25@gmail.com> a
écrit :

**Comment by jk-q** [comment]
It's good.
