### ISSUE TITLE
Надоели ложные обновления с ошибками

### ISSUE THREAD

**Issue by FrostSigil** [hsdn/tera-guide#48]
Здравствуйте
Каждый день вы пилите обновления, но не проверяете их даже элементарным тестом загрузится ли мод при входе в игру..
сколько раз уже натыкаюсь на отказ работоспособности мода когда он местами необходим моим друзьям..
Пожалуйста хотя бы тестируйте перед выгрузкой обновления в открытую сеть.
Спасибо)

**Comment by jk-q** [comment]
Перед каждой загрузкой обновления все досконально тестируется на нескольких сборках TeraToolbox, в том числе проверяются миграции со старых версий tera-guide. Любые ошибки исключены. 

Однако мы не исключаем ошибки кэша github (несовпадение хэш-суммы в manifest.json), но это явление временное, которое обычно проходит спустя 2-3 минуты.

**Comment by jk-q** [comment]
Также настоятельно рекомендую прикладывать лог ошибок TeraToolbox при создании запроса на github. В противном случае мы можем дать лишь общие рекомендации, основанные на предположениях исходя из прошлого опыта по решению проблем.

**Comment by beng-mods** [comment]
потому что лапки должны быть в тепле
