### ISSUE TITLE
Character Buffs (Prime battle solution, Bravery, Noct, Etc.)

### ISSUE THREAD

**Issue by AnjeloTing** [hsdn/tera-guide#49]
No error shown in Toolbox but when you go inside dungeons it starts to not show anything, some skills doesn't work due to no buffs like 2nd tap Godsfall or Shining Crescent.

**Comment by jk-q** [comment]
Hi. What dungeon?

**Comment by justkeepquiet** [comment]
Install the latest updates, this issue should be fixed.

**Comment by AnjeloTing** [comment]
I tried DAH, DAN, CSN same for all. Now fixed. Thank you!
