### ISSUE TITLE
Corrupted Skynest "error running hook"

### ISSUE THREAD

**Issue by S1m4k** [hsdn/tera-guide#5]
[dispatch] [tera-guide] handle: error running hook for S_ABNORMALITY_BEGIN<4>
hook: abnormality_triggered in tera-guide
data: {
  target: 140737490259730n,
  source: 0n,
  id: 4610,
  duration: 25675062n,
  stacks: 1,
  hitCylinderId: 0,
  unk3: 2
}
error: Cannot read property 'mobs' of undefined
    at Object.abnormality_triggered [as callback] (D:\Games\TeraToolbox\mods\tera-guide\index.js:219:30)

**Comment by shindmitry** [comment]
Hi,
What is your region? Did the error happen once or is it repeated regularly?
We tested this dungeon in update NA 95.03 today, no errors was detected.

**Comment by S1m4k** [comment]
Hi
Im from EU
It repeated regularly and bot only in CS but GLS as well
I've dowloaded both this and library mods yday but i'll doublecheck for updates

**Comment by shindmitry** [comment]
If an error is detected, we will make fixes. Thanks.

**Comment by S1m4k** [comment]
Just updated library one - now everything works
It seems that the last changes were made at a time while my toolbox was running so there were no fixes
Thanks and sorry for your time
