### ISSUE TITLE
RU version bugs since 13/11/2020

### ISSUE THREAD

**Issue by JuilkaOrange** [hsdn/tera-guide#51]
1. Doesn't work russian voice notifications (always in english)
2. Doesn't work russian text notifications (always in english)
3. UI looks like this:
![image](https://user-images.githubusercontent.com/74449703/99143925-b857bf00-268b-11eb-97c9-d1fb2f48aa04.png)

**Comment by jk-q** [comment]
Hi,
I checked now. No problems were found (tested on RU client with patch 99.2).

Try to close Toolbox and delete _config.json_ in the module folder or fully reinstall guide module.
Also check uptates of _tera-game-state_ and _library_ modules.

In addition, you can try changing the language to English and then back to Russian in the gameforge launcher.

**Comment by jk-q** [comment]
Если все это не помогло, напишите мне в дискорд **JKQ#5649** (можно на русском).

**Comment by JuilkaOrange** [comment]
Спасибо, проблема была в tera-game-state.

**Comment by knoxieeee** [comment]
Привет,скажи пожалуйста как ты устранил ошибку?

**Comment by jk-q** [comment]
Проблема, описанная автором данного запроса, была связана с модулем "tera-game-state", который необходимо было обновить для ее устранения.

**Comment by knoxieeee** [comment]
Напишите пожалуйста,как обновить модуль

**Comment by jk-q** [comment]
Включите автоматическое обновление модулей в Toolbox (если выключено), после чего просто перезапустите программу. Если это не помогло - полностью удалите Toolbox и скачайте заново последнюю версию, после чего установите нужные модули.

**Comment by knoxieeee** [comment]
Большое спасибо за помощь
