### ISSUE TITLE
''Spawn_dropitem is outdated and cannot be used anymore''

### ISSUE THREAD

**Issue by SendHelPlz** [hsdn/tera-guide#52]
![image](https://user-images.githubusercontent.com/68261242/99194657-90399000-275f-11eb-860d-968a7090e75d.png)
after the migration of the NA server to the gameforge, it updated to version 99, and after that the guide started to present a problem, it freezes the game and only works again after pressing ok, it is occurring in bahaar and DAH, however the guide works normal if you disable the objects in the guide gui

**Comment by jk-q** [comment]
You using outdated version of the module. Please update to the latest version before opening a issue.

**Comment by SendHelPlz** [comment]
> You using outdated version of the module. Please update to the latest version before opening a issue.

worked, thank you 

![image](https://user-images.githubusercontent.com/68261242/99202357-a2322780-278d-11eb-88fe-4f4bdab4f9cd.png)
