### ISSUE TITLE
SCEM

### ISSUE THREAD

**Issue by littleguideboi** [hsdn/tera-guide#53]
Will there be a guide for SCEM ?

**Comment by jk-q** [comment]
Hi, this guide has already added. Please install updates.

**Comment by littleguideboi** [comment]
I saw you guys added but, when he doing the back attacks, it doesn't specify if it's 4 times or 3 times or 2 times. Fix maybe?

**Comment by jk-q** [comment]
This should be fixed in latest versions. Most of the work is in progress, many may not work.
