### ISSUE TITLE
Tera guide doesn't work

### ISSUE THREAD

**Issue by Daryjo** [hsdn/tera-guide#56]
ERROR: Module "Guide" (tera-guide) could not be applied to server connection!
TypeError: Cannot destructure property 'player' of 'mod.require.library' as it is null.

**Comment by jk-q** [comment]
You need update Toolbox and reinstall **library** module.
https://github.com/tera-toolbox-mods/library

**Comment by Daryjo** [comment]
> You need update Toolbox and reinstall **library** module.
> https://github.com/tera-toolbox-mods/library

Already did that twice. Still doesn't work

**Comment by jk-q** [comment]
Try add guide to the fresh installed Toolbox (not beta branch).
