### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by VitaliR7** [hsdn/tera-guide#62]
An error appears at server connection.

Here is the log:
[11:09:58.952] [mods] ERROR: Module "Guide" (Guide-Mod) could not be applied to server connection!
[11:09:58.955] [mods] ERROR: Please contact the module's author: https://github.com/multarix/tera-guide-revised/issues
[11:09:58.958] Error: Command already registered: guide
    at CommandBase.add 
\AppData\Local\Programs\TeraToolbox\mods\command\index.js:255:19)
 at Command.add \AppData\Local\Programs\TeraToolbox\mods\command\index.js:407:19)
at new TeraGuide AppData\Local\Programs\TeraToolbox\mods\tera-guide-revised\index.js:152:6)
at new <anonymous> AppData\Local\Programs\TeraToolbox\bin\mod-legacy-wrapper.js:144:13)
at Mod.loadNetworkInstance \AppData\Local\Programs\TeraToolbox\bin\mod.js:595:31)
at ModManager.loadNetwork \AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:252:20)
at AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:233:22
at Map.forEach (<anonymous>) 
at ModManager.loadAllNetwork  AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:231:25)
at Socket.<anonymous> \AppData\Local\Programs\TeraToolbox\bin\connection-manager.js:59:33)

**Comment by VitaliR7** [comment]
OK never mind.)

**Comment by jk-q** [comment]
Hi. It is not our guide module.
