### ISSUE TITLE
mm guide

### ISSUE THREAD

**Issue by jvsant0s** [hsdn/tera-guide#63]
dont work as inteded, just notify stuns, lines, pulls and jumps

**Comment by jk-q** [comment]
Hi. For the complete work of the guide, the support of the packet **S_DUNGEON_EVENT_GAGE** map is needed.
This map file you can be install from in the https://github.com/PsykoDev/Full-Opcode-Tera-EU-NA near future, I think.
At the moment this map is not yet available.

**Comment by ambushing** [comment]
if you're so trap that you need an immediate solution, or just want to use a mod instead of a map file: https://github.com/ambushing/pls-learn-manglemire

**Comment by jk-q** [comment]
Thanks for you solution. We add this code to the guide. Issue closed.
