### ISSUE TITLE
Tera-guide

### ISSUE THREAD

**Issue by Motazkhalaf** [hsdn/tera-guide#68]
![Capture](https://user-images.githubusercontent.com/91265200/134515401-b39d3e23-af07-4227-a4dc-0f10f79dd2b3.JPG)
 
any idea how to fix this?

**Comment by jk-q** [comment]
Hi. You are using a outdated tera-guide module. 
Just use the latest version of our module from https://github.com/hsdn/tera-guide

**Comment by Motazkhalaf** [comment]
@jk-q  can u pls give me a link to download or a screan shot where to click i am a bit lost cant find away to download it .-. sorry

**Comment by jk-q** [comment]
https://github.com/hsdn/tera-guide/archive/refs/heads/master.zip

**Comment by Motazkhalaf** [comment]
![Capture](https://user-images.githubusercontent.com/91265200/134517435-ba4183ce-d0af-4daf-9e76-ec53b8e32746.JPG)
 i downloaded it but i cant see any setup or exe for the toolbox app 
sorry again if i am annoying :3 pls  bear with me
@jk-q

**Comment by jk-q** [comment]
You need to place this directory in your **mods** folder. The old version of the tera-guide must be removed.

**Comment by jk-q** [comment]
For more information about installing modules from github, you can ask in the Toolbox official discord https://discord.gg/dUNDDtw

**Comment by Motazkhalaf** [comment]
thanks for the fast response and info .
