### ISSUE TITLE
DAHM

### ISSUE THREAD

**Issue by Amethsya** [hsdn/tera-guide#7]
First of all, this's a question but i don't know how to label it. So, please accept my apology since i'm openning it as issue.

When i use your guide in DANM, it puts red color areas on the floor according to boss attack. For instance, when boss about to do front hit and back kick, guide marks the zone w/ red or the pizza attack thing.

But in DAHM, this feature doesn't work. Is it intended or just me having this weird situation.

**Comment by shindmitry** [comment]
Hi, this functionality is implemented in both the DANM and DAHM. That should work.

A notification "Front-back pizza" is displayed for you at the time of this attacks?

**Comment by Amethsya** [comment]
Hi Dmitry, thanks for answering ^^

is this your mod doing red area on the floor? You can check in it in the link.

https://1.bp.blogspot.com/-9xB-MVRMhoM/XqHHGWqBcAI/AAAAAAAAAls/sIG77TRnV3UotbM3r_LAjrjAqRzPjUiFwCEwYBhgL/s1600/%25EC%2595%259E%25EC%25BF%25B5%25EB%2592%25B7%25EB%25B0%2580%25EC%25B9%2598%25EA%25B8%25B0.gif


If tera-guide does this red warning zone, it does on normal mode but not on hard mode.

**Comment by shindmitry** [comment]
Your link shows the game built-in zone (not proxy), only available for normal mode.
