### ISSUE TITLE
menma

### ISSUE THREAD

**Issue by IM02** [hsdn/tera-guide#74]
does this work for menma server ?

**Comment by jk-q** [comment]
https://github.com/hsdn/tera-guide/blob/master/README.md

**Comment by jk-q** [comment]
### :information_source: About patch 92 support   
Technically, the tera-guide and [tera-guide-core](https://github.com/hsdn/tera-guide-core) are compatible with patch 92 already, but not all old guides have been added. You can get the needed guide files manually from the [tera-guide-archive](https://github.com/hsdn/tera-guide-archive).   
You will also need an compatible version of the **library** ([download here](https://git.dev.hsdn.org/tera-v92/library/archive/master.zip)).

In the future, after the official server of Tera is closed, we will release a complete version of the guide for patch 92.

**Comment by jk-q** [comment]
Full support for patch v92.04 (Menma) has been added.
