### ISSUE TITLE
asura 92.04

### ISSUE THREAD

**Issue by sasha5434** [hsdn/tera-guide#75]
hi, asura server have more dungeons

**Comment by jk-q** [comment]
Hi, dungeon names?

**Comment by sasha5434** [comment]
all dungeon added before 92.94

**Comment by jk-q** [comment]
List of all available guides is here https://github.com/hsdn/tera-guide-archive
We do not have other guides and its creation is not planned yet.

**Comment by jk-q** [comment]
Добавлены следующие данжи:
* **Секретное подземелье крепости Берарк**
* **Логово Келсаика**
* **Лаборатория Берна (сложно)**
* **Руины Кошмарной Абнукты**

Если будут созданы гайды на недостающие данжи, они также будут добавлены.
По всем вопросам и предложениям можно обращаться в дискорд.
