### ISSUE TITLE
Add a guide for 9983

### ISSUE THREAD

**Issue by TristPW** [hsdn/tera-guide#78]
Hi!
Add a guide for 9983 in, please )

**Comment by justkeepquiet** [comment]
Temporarily you can use this code:
https://github.com/michengs/tera-guide/issues/8#issuecomment-1159567179
An updated Russian version will be added in the future.

**Comment by TristPW** [comment]
This code works except for three errors.

[tera-guide] ERROR: Key "load" has invalid type.
[tera-guide] ERROR: Limit of records for key "s-783-2000-318-0" exceeded.
[tera-guide] ERROR: Limit of records for key "s-783-3000-303-0" exceeded.
[tera-guide] ERROR: Limit of records for key "s-783-3000-306-0" exceeded.

It looks like the error appears when using concat().

**Comment by justkeepquiet** [comment]
The guide for dungeon Dark Reach Citadel (Hard) has been added.
