### ISSUE TITLE
TTS

### ISSUE THREAD

**Issue by LeGiam** [hsdn/tera-guide#8]
My tts volume is low af, idk if i did something or the guide did it byitself, how do i fix it?
It wasnt always like that, it used to work fine

**Comment by shindmitry** [comment]
Try turn down the TERA volume and turn up the master volume in the Windows.

**Comment by LeGiam** [comment]
my master volume is always at 100 and tera is lowish as it always have been, is there any way to set up the TTS volume itself?

**Comment by shindmitry** [comment]
TTS in the proxy module does not have a separate volume setting.

**Comment by shindmitry** [comment]
The TTS voice is processed by the program Powershell.exe, for which the volume must be set in Windows if it is not set. 
![](https://i.imgur.com/uhExTbC.png)

Try reset all volume settings in your mixer.

**Comment by LeGiam** [comment]
Thanks a lot, my windows powershell volume was set to "2" somehow lmao. Fixed it!
