### ISSUE TITLE
Sky Cruiser (Hard)

### ISSUE THREAD

**Issue by zonze37250** [hsdn/tera-guide#81]
Sky Cruiser broken?

**Comment by justkeepquiet** [comment]
There is currently no guide for this dungeon.

**Comment by zonze37250** [comment]
yet it is in the list

**Comment by justkeepquiet** [comment]
It is SCE from patch 115.

You need:
9716 Sky Cruiser Endeavor
9916 Sky Cruiser Endeavor (Hard)

**Comment by zonze37250** [comment]
Ha ok, I understand better, but if there is none, I will do without!

**Comment by justkeepquiet** [comment]
Guides has been added.
