### ISSUE TITLE
9770's "Get Ready!" follow-up callout broken

### ISSUE THREAD

**Issue by cloudysunrise** [hsdn/tera-guide#82]
The messages from **[s-770-3000-1304-0](https://github.com/hsdn/tera-guide/blob/master/guides/9770.js#L103=)** and **[s-770-3000-1303-0](https://github.com/hsdn/tera-guide/blob/master/guides/9770.js#L104=)** appear ("Get Ready!") but the follow-up messages **[s-770-3000-1113-0](https://github.com/hsdn/tera-guide/blob/master/guides/9770.js#L105=)** ("Out" then "In") and **[s-770-3000-1116-0](https://github.com/hsdn/tera-guide/blob/master/guides/9770.js#L110=)** ("In" then "Out") no longer appear.

**Comment by justkeepquiet** [comment]
Fixed.
