### ISSUE TITLE
Early notice for in out mechanics.

### ISSUE THREAD

**Issue by Aki62** [hsdn/tera-guide#83]
Hello, it would be nice if the guide can tell where to position earlier during red magic / pizza mechanic in AANM/AAHM/DAHM ie:  in to out, out to in. Thank you.

**Comment by justkeepquiet** [comment]
Please contact with the guides developer https://github.com/emilia-s2

**Comment by Aki62** [comment]
Okay, Thank you. Just to be sure since I use the English guide, does Emilia work on English guides too? It says Español/Portuguese in his/her repositories.

**Comment by justkeepquiet** [comment]
All changes from Emilia are merging into our localization (Russian/English).

**Comment by emilia-s2** [comment]
My version is set as default in portuguese, however it has full support with (spanish and english)
